[tool.poetry]
name = "notion"
version = "0.1.0"
description = ""
authors = ["yuchenleejj <255234justin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
